config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  root 'products#index'
  resources :products do
    resources :comments
  end
  resources :shopping_carts
  resources :orders
  resources :logs
  resources :order_details
  resources :like_products
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :products
      resources :sessions
      resources :users
    end
  end
  resources :users do
    resources :comments
  end
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :product

  validates :quantity, numericality: { greater_than_or_equal_to: 1 }, on: :create

  def self.update_quantity(quantity, prd, type)
    if type
      prd.quantity -= quantity.to_i
    else
      prd.quantity += quantity.to_i
    end
    prd.save
    if prd.quantity.to_i <= 3 && !prd.like_products.empty?
      SendNotificationsJob.perform_later(prd)
    end
  end

  def self.cart_list(user_id, product_id, quantity)
    list = ShoppingCart.find_by(user_id: user_id, product_id: product_id)
    list.quantity += quantity.to_i if list
    list
  end

  def category_name
    product.category.name
  end

  def product_name
    product.product_name
  end

  def prod_sku
    product.sku
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :user_id
  before_action :prd, only: %i[create destroy]
  before_action :prod, only: :index
  helper_method :prod
  def index
    @total = 0
    if user_signed_in?
      if !current_user.admin?
        seed_cart
      else
        error(products_path, 'You can\'t buy')
      end
    end
  end

  def new
    @shopping_cart = ShoppingCart.new
  end

  def destroy
    @cart_delete = ShoppingCart.find_by(user_id: @user_id, product_id: params[:id])
    if @cart_delete.destroy
      ShoppingCart.update_quantity(@cart_delete.quantity, @prd, false)
      success(shopping_carts_path, 'Product deleted successfully.')
    else
      error(shopping_carts_path, 'Product was not deleted.')
    end
  end

  def create
    @cart_list = ShoppingCart.cart_list(@user_id, @prd.id,
                                        params[:shopping_cart][:quantity])
    @cart_list ||= ShoppingCart.new(car_params)
    if @cart_list.save
      ShoppingCart.update_quantity(params[:shopping_cart][:quantity], @prd, true)
      success(shopping_carts_path, 'Product added successfully.')
    else
      error(shopping_carts_path, 'Product was not added.')
    end
  end

  private

  def car_params
    params.require(:shopping_cart).permit(:product_id, :quantity, :price).merge(
      user_id: @user_id
    )
  end

  def user_id
    @user_id = if user_signed_in?
                 current_user.id
               else
                 unless session[:current_user_id]
                   session[:current_user_id] =
                     SecureRandom.random_number(999_999)
                 end
                 session[:current_user_id]
               end
  end

  def seed_cart
    if session[:current_user_id]
      @product_session = ShoppingCart.all.where(user_id: session[:current_user_id])
      if @product_session
        @product_session.each do |item|
          item.user_id = current_user.id
          item.save
        end
      end
      session[:current_user_id] == ''
    end
  end

  def prd
    @prd = if action_name == 'create'
             Product.find(params[:shopping_cart][:product_id])
           else
             Product.find(params[:id])
           end
  end

  def prod
    @prod =
      if user_signed_in?
        unless current_user.admin?
          ShoppingCart.all.where(user_id:
            current_user.id).includes(product: :category)
        end
      else
        ShoppingCart.all.where(user_id:
          session[:current_user_id]).includes(product: :category)
      end
  end
end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper
end

app/views/shopping_carts/_cart_list.html.erb
<tbody>
  <%  prod.each do |produ| %>
    <tr>
      <td data-th="Product">
        <div class="row">
          <div class="col-sm-2 hidden-xs"></div>
          <div class="col-sm-10">
            <h4 class="nomargin"><%= produ.prod_sku%></h4>
            <p><%= produ.product_name%></p>
            <p><%= produ.category_name%></p>
          </div>
        </div>
      </td>
      <td data-th="Price"><%= number_to_currency produ.price%></td>
      <td data-th="Quantity" style="text-align: center;">
        <p><%= produ.quantity %></p>
      </td>
      <td data-th="Subtotal" class="text-center"><%=number_to_currency (produ.price.to_f * produ.quantity)%></td>
      <td class="actions" data-th="">
        <td><%= link_to '<button class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></button>'.html_safe, shopping_cart_path(:id => produ.product_id),data: { confirm: "Are you sure?" }, method: :delete%>
          <br/>
        </td>
      </tr>
      <%@total += (produ.price * produ.quantity)%>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td>
        <a href="./products" class="btn btn-warning">
          <i class="fa fa-angle-left"></i>
          Continue Shopping</a>
      </td>
      <td colspan="2" class="hidden-xs"></td>
      <td class="hidden-xs text-center">
        <strong>Total
          <%= number_to_currency @total%></strong>
      </td>
      <%if user_signed_in?%>
      <td><%= link_to '<button class="btn btn-success btn-block" type="button">Checkout</button>'.html_safe, orders_path, method: :post%> </td>
      <% else %>
      <td><%= link_to '<button class="btn btn-success btn-block" type="button">Sign In</button>'.html_safe, new_user_session_path%> </td>
      <% end %>
    </tr>
  </tfoot>

app/views/shopping_carts/index.html.erb
<br>
<% if flash[:alert] %>
  <div class="alert alert-<%= flash[:alert_type]%>" role="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%=flash[:alert]%>
  </div>
<% end %>
<br>
<div class="container">
  <table id="cart" class="table table-hover table-condensed">
    <thead>
      <tr>
        <th style="width:50%">Product</th>
        <th style="width:10%">Price</th>
        <th style="width:8%">Quantity</th>
        <th style="width:22%" class="text-center">Subtotal</th>
        <th style="width:10%"></th>
      </tr>
    </thead>
    <%= render "cart_list" %>
    </table>
  </div>