config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  root 'products#index'
  resources :products do
    resources :comments
  end
  resources :shopping_carts
  resources :orders
  resources :logs
  resources :order_details
  resources :like_products
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :products
      resources :sessions
      resources :users
    end
  end
  resources :users do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  validates :review, presence: true, allow_blank: false
  def comment_user(id)
    User.find(id).username
  end

  def comment_status(status)
    if status == 'A'
      'Activated'
    else
      'Disabled'
    end
  end
end

app/models/like_product.rb
class LikeProduct < ApplicationRecord
  belongs_to :user
  belongs_to :product, counter_cache: :likes_count
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details
  has_many :products, through: :order_details

  def self.seed_detail(product, last_order,id)
    product.each do |val|
      @detail = OrderDetail.new(order: last_order,
                                product: val.product,
                                quantity: val.quantity,
                                price: val.price,
                                status: 'P')
      ShoppingCart.where(user_id: id, product: val.product).destroy_all if @detail.save
    end
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, numericality: { greater_than_or_equal_to: 1 }, on: :create
end

app/models/product.rb
class Product < ApplicationRecord
  # relations
  belongs_to :category
  has_many :order_details
  has_many :log
  has_many :shopping_cart
  has_many :orders, through: :order_details
  has_many :like_products
  has_one_attached :image
  has_many :comments, as: :commentable

  # validations
  validates :sku, :product_name, presence: true
  validates :sku, uniqueness: true
  validates :quantity, numericality: {
    greater_than_or_equal_to: 0
  }, on: :create

  # scopes
  scope :sort_scope, ->(sort_val) { order(sort_val) }
  scope :term_scope, lambda { |term_val|
                       where('product_name ILIKE ?', "%#{term_val}%")
                     }
  scope :category_scope, ->(category_val) { where category_id: category_val }
  scope :page_scope, ->(page_val) { paginate(page: page_val, per_page: 8) }

  def category_name
    category.name
  end

  def image_attach?
    image.attached?
  end

  def big_image
    image.variant(resize: '200x200')
  end

  def medium_image
    image.variant(resize: '100x100')
  end

  def like_size
    like_products.size
  end

  def like_user(prod, id)
    prod.like_products.where(user_id: id)
  end

  def self.price_log(product, old_price, id)
    @log = Log.new(user_id: id,
                   description: 'The price of the product has change',
                   product_id: product.id, old_price: old_price,
                   new_price: product.price)
    @log.save
  end

  def rating
    comments.where("status='A' AND rating > 0 ").average(:rating)
  end
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :product

  validates :quantity, numericality: { greater_than_or_equal_to: 1 }, on: :create

  def self.update_quantity(quantity, prd, type)
    if type
      prd.quantity -= quantity.to_i
    else
      prd.quantity += quantity.to_i
    end
    prd.save
    if prd.quantity.to_i <= 3 && !prd.like_products.empty?
      SendNotificationsJob.perform_later(prd)
    end
  end

  def self.cart_list(user_id, product_id, quantity)
    list = ShoppingCart.find_by(user_id: user_id, product_id: product_id)
    list.quantity += quantity.to_i if list
    list
  end

  def category_name
    product.category.name
  end

  def product_name
    product.product_name
  end

  def prod_sku
    product.sku
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: %i[user admin]
  after_initialize :set_default_role

  def set_default_role
    self.role ||= :user if new_record?
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :shopping_cart
  has_many :log
  has_many :order
  has_many :comments, as: :commentable

  def rating
    comments.where("status='A' AND rating > 0").average(:rating)
  end
end

app/controllers/api/v1/users_controller.rb
module API
  module V1
    class UsersController < ApplicationController
      def index
        rkey = '82a4ca11-464c-49ae-ab3c-9c9f99909b0d'
        data = request.headers['token']
        begin
          decoded = JWT.decode data, rkey, true, algorithm: 'HS256'
          user_id = decoded[0]['user_id']
          @user = User.find(user_id)
          render json: { user: @user }
        rescue JWT::VerificationError
          render json: { info: 'token expired' }, status: :unathorized
        rescue StandardError
          render json: { info: 'user not found' }, status: :not_found
        end
      end
    end
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end

  def create
    @product = ShoppingCart.all.where(user_id: current_user.id)
    @order = Order.new(user_id: current_user.id, status: 'N')
    @order.save
    @last = Order.last
    Order.seed_detail(@product,@last,current_user.id) if @product
    @last.status = 'P'
    @last.save
    success(products_path, 'Order created successfully.')
  rescue StandardError
    error(products_path, 'Order was not created.')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :user, :exist, :users, :comments
  helper_method :user, :users, :comments
  # before_action :admin_only, except: :show

  def index; end

  def show
    @comment = @user.comments.new
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

  def comments
    @comments =
      if action_name == 'index'
        Comment.all.where("commentable_type='User'")
      else
        @user.comments.where(status: 'A').includes(:user)
      end
  end

  def users
    @users = User.where(role: :user)
  end

  def user
    @user =
      if params[:id].present?
        User.find_by(id: params[:id])
      else
        current_user
      end
  end

  def exist
    error(user_path(id: current_user.id), 'User not available') unless @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def boostrap_class(alert)
    { success: 'alert-success', error: 'alert-danger', notice: 'alert-success', warning: 'alert-warning',
      danger: 'alert-danger', alert: 'alert-danger' }[alert.to_sym]
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{boostrap_class(msg_type.to_sym)} fade in") do
        concat(content_tag(:button, id: 'close-button', class: 'close', type: :button, data: { dismiss: 'alert' }, 'aria-label' => :Close) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/like_products_helper.rb
module LikeProductsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/rol_helper.rb
module RolHelper
end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper
end

app/views/users/_comments.html.erb
<tbody>
  <%  comments.each do |comment| %>
    <tr>
      <td class="text-center">
        <%= comment.review%></td>
      <td class="text-center"><%= comment.user.username%></td>
      <td class="text-center"><%= comment.comment_user(comment.commentable_id) %></td>
      <td class="text-center"><%=comment.comment_status(comment.status)%></td>
      <%if comment.status=='D'%>
      <td><%= link_to '<button class="btn btn-primary btn-sm"><i class="fas fa-check-circle"></i></button>'.html_safe, comment_path(:id => comment.id),data: { confirm: "Are you sure?" }, method: :put%>
      <%else%>
      <td><%= link_to '<button class="btn btn-danger btn-sm"><i class="fas fa-minus-circle"></i></button>'.html_safe, comment_path(:id => comment.id),data: { confirm: "Are you sure?" }, method: :put%>
      <%end%>
      <%= link_to '<button class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></button>'.html_safe, comment_path(:id => comment.id),data: { confirm: "Are you sure?" }, method: :delete%></td>

    </tr>
  <% end %>
</tbody>
<tfoot>
  <tr>
    <td>
      <a href="./products" class="btn btn-warning">
        <i class="fa fa-angle-left"></i>
        See Products</a>
    </td>
    <td colspan="4" class=""></td>
  </tr>
</tfoot>

app/views/users/_new_comment.html.erb
<%if user_signed_in? && !current_user.admin? && !@user.admin?%>
<div class="col-md-2"></div>
<div style="width:60%;" class="col-md-12">
<h2 style="color: blue;">
  New Comment:
</h2>
  <div class="col-sm-10">
    <%= form_for @comment, :url => user_comments_url(@user), :method => :post do |form| %>
    <div class="field" style="width: 50%">
      <%= form.text_area :review, :cols => 60, :rows => 4, style: "color: 	#000000;", :required => true%>
    </div>
    <label style= "color: #000000;" >Rate me:</label>
    <%= form.radio_button :rating, 1, :id=>"one", :style=>"display:none;", :checked => false, class: "check-with-label"  %>
    <label style= "-webkit-text-stroke-width: 1px;-webkit-text-stroke-color: yellow;" for="one" class="label-for-check fas fa-star"></label>
    <%= form.radio_button :rating, 2, :id=>"two", :style=>"display:none;", :checked => false, class: "check-with-label"  %>
    <label style= "-webkit-text-stroke-width: 1px;-webkit-text-stroke-color: yellow;" for="two" class="label-for-check fas fa-star"></label>
    <%= form.radio_button :rating, 3, :id=>"thre", :style=>"display:none;", :checked => false, class: "check-with-label"  %>
    <label style= "-webkit-text-stroke-width: 1px;-webkit-text-stroke-color: yellow;" for="thre" class="label-for-check fas fa-star"></label>
    <%= form.radio_button :rating, 4, :id=>"four", :style=>"display:none;", :checked => false, class: "check-with-label"  %>
    <label style= "-webkit-text-stroke-width: 1px;-webkit-text-stroke-color: yellow;" for="four" class="label-for-check fas fa-star"></label>
    <%= form.radio_button :rating, 5, :id=>"five", :style=>"display:none;", :checked => false, class: "check-with-label"  %>
    <label style= "-webkit-text-stroke-width: 1px;-webkit-text-stroke-color: yellow;" for="five" class="label-for-check fas fa-star"></label>
    <div class="actions">
      <%= form.submit style: "color: 	#000000;"%>
    </div>
  <%end%>
</div>
<%end%>
</div>

app/views/users/_user_comment.html.erb
<%unless comments.empty?%>
<div class="col-md-2">

</div>
<div style="width:60%;" class="col-md-12">
    <div class="col-sm-8">
  <h1 style="color: blue;">
    Comments:
  </h1>
  </div>
    <% comments.each do |comment| %>
    <div class="col-sm-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <strong><%= link_to comment.user.username, user_path(:id => "#{comment.user.id}") %></strong>
            <span class="text-muted"><%=comment.created_at.getlocal.strftime("%m/%d/%Y at %I:%M %p")%></span>
          </div>
          <div class="panel-body text-muted">
            <%=comment.review%>
          </div>
        </div>
      </div>
    <%end%>
  <%end%>

app/views/users/_user_information.html.erb
<div class="col-md-4"></div>
<div style="width:40%;" class="thumbnail col-md-6">
<div class="col-sm-12">
<h1 style="color: blue;">
  Profile
</h1>
</div>
<br>
  <div class="caption">
    <div class="row">
      <div class="col-xs-12 col-md-12">
      <p>  <label>UserName</label>    <%= user.username %></p>
      <p>  <label>Email</label>    <%= user.email %></p>
      <p><label>Rating:</label><%= user.rating %>  <i class="fas fa-star" style="color:yellow;"></i></p>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<br>
<% if flash[:alert] %>
  <div class="alert alert-<%= flash[:alert_type]%>" role="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%=flash[:alert]%>
  </div>
<% end %>
<br>
<div class="container">
  <table id="cart" class="table table-hover table-condensed text-center">
    <thead>
      <tr>
        <th class="text-center" style="width:20%">Review</th>
        <th class="text-center" style="width:20%">From User</th>
        <th class="text-center" style="width:8%">To User</th>
        <th class="text-center" style="width:22%" class="text-center">Status</th>
        <th class="text-center" style="width:10%">Modify</th>
      </tr>
    </thead>
    <%= render "comments" %>
    </table>
  </div>

app/views/users/show.html.erb
<% if flash[:alert] %>
  <div class="alert alert-<%= flash[:alert_type]%>" role="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%=flash[:alert]%>
  </div>
<% end %>
<br><br>
<table align="center" border="0" width="90%">
  <tr>
    <td rowspan="3" style="background-color: #F5F5F5;"  width="20%" valign="top">
      <div class="shop-tab-menu">
        <h1 style="color: black;text-align: center;">Users</h1>
        <br><br>
        <div class="list-group">
          <%  users.each do |user| %>
            <%= link_to raw("<button class='list-group-item fas fa-user' type='button'>  #{user.username}</button>"), user_path(:id => "#{user.id}")%>
            <br>
          <% end %>
        </div>
      </div>
    </td>
    <td style="background-color: #F5F5F5;">
      <%= render "user_information"%>
    </td>
  </tr>
  <tr>
    <td style="background-color: #F5F5F5;">
      <%= render "user_comment" %>
    </td>
  </tr>
  <tr>
    <td style="background-color: #F5F5F5;">
        <%= render "new_comment"%>
      </td>
    </tr>

  </table>