config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  root 'products#index'
  resources :products do
    resources :comments
  end
  resources :shopping_carts
  resources :orders
  resources :logs
  resources :order_details
  resources :like_products
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :products
      resources :sessions
      resources :users
    end
  end
  resources :users do
    resources :comments
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # relations
  belongs_to :category
  has_many :order_details
  has_many :log
  has_many :shopping_cart
  has_many :orders, through: :order_details
  has_many :like_products
  has_one_attached :image
  has_many :comments, as: :commentable

  # validations
  validates :sku, :product_name, presence: true
  validates :sku, uniqueness: true
  validates :quantity, numericality: {
    greater_than_or_equal_to: 0
  }, on: :create

  # scopes
  scope :sort_scope, ->(sort_val) { order(sort_val) }
  scope :term_scope, lambda { |term_val|
                       where('product_name ILIKE ?', "%#{term_val}%")
                     }
  scope :category_scope, ->(category_val) { where category_id: category_val }
  scope :page_scope, ->(page_val) { paginate(page: page_val, per_page: 8) }

  def category_name
    category.name
  end

  def image_attach?
    image.attached?
  end

  def big_image
    image.variant(resize: '200x200')
  end

  def medium_image
    image.variant(resize: '100x100')
  end

  def like_size
    like_products.size
  end

  def like_user(prod, id)
    prod.like_products.where(user_id: id)
  end

  def self.price_log(product, old_price, id)
    @log = Log.new(user_id: id,
                   description: 'The price of the product has change',
                   product_id: product.id, old_price: old_price,
                   new_price: product.price)
    @log.save
  end

  def rating
    comments.where("status='A' AND rating > 0 ").average(:rating)
  end
end

app/controllers/api/v1/products_controller.rb
module API
  module V1
    class ProductsController < ApplicationController
      def index
        @product = Product.where("status='A'")
        @product = @product.category_scope(@category) if @category
        @product = @product.sort_scope('product_name ASC') unless @sort
        @product = @product.sort_scope(@sort) if @sort
        @product = @product.term_scope(@term) if @term
        @product = @product.page_scope(@page).includes(
          :category, :like_products
        )
        respond_to do |format|
          format.json { render json: @product }
        end
      end
    end
  end
end

app/controllers/products_controller.rb
require 'securerandom'
class ProductsController < ApplicationController
  before_action :set_cache_headers
  before_action :product, :category, :exist
  helper_method :product, :category
  before_action :admin_only, only: %i[new create edit update destroy]
  before_action :values, only: :index
  before_action :comments, only: :show
  helper_method :comments
  def index
    @product = @product.category_scope(@category) if @category
    @product = @product.sort_scope('product_name ASC') unless @sort
    @product = @product.sort_scope(@sort) if @sort
    @product = @product.term_scope(@term) if @term
    @product = @product.page_scope(@page).includes(
      :category, :like_products
    )
  end

  def show
    @shopping_cart = ShoppingCart.new
    @comment = @product.comments.new
  end

  def new; end

  def create
    if @product.save
      success(products_path, 'Product created successfully.')
    else
      error(new_product_url, 'Product was not created.')
    end
  end

  def edit; end

  def update
    old_price = @product.price
    @product.assign_attributes(update_params)
    if @product.save
      if old_price != params[:product][:price]
        Product.price_log(@product, old_price, current_user.id)
      end
      success(products_path, 'Product updated successfully.')
    else
      render 'edit'
    end
  end

  def destroy
    @product.status = 'D'
    if @product.save
      success(products_path, 'Product deleted successfully.')
    else
      error(products_path, 'Product was not deleted.')
    end
  end

  private

  def product
    @product ||=
      if action_name == 'new'
        Product.new
      elsif %w[update edit show destroy].include?(action_name)
        Product.find_by(id: params[:id])
      elsif action_name == 'create'
        Product.new(post_params)
      else
        Product.with_attached_image.where("status='A'")
      end
  end

  def category
    @category = Category.all.order('name ASC')
  end

  def post_params
    params.require(:product).permit(
      :quantity, :product_name, :price, :category_id, :image, :sku, :status
    )
  end

  def update_params
    params.require(:product).permit(
      :quantity, :product_name, :price, :category_id, :image
    )
  end

  def set_cache_headers
    response.headers['Cache-Control'] =
      'no-cache, no-store, max-age=0, must-revalidate'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = 'Fri, 01 Jan 1990 00:00:00 GMT'
  end

  def values
    @category = params[:category]
    @sort = params[:sort]
    @term = params[:term]
    @page = params[:page]
  end

  def comments
    @comments = @product.comments.where(status: 'A')
  end

  def exist
    error(products_path, 'Product not available') unless @product
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/products/_list_comments.html.erb
<%unless comments.empty?%>
  <h2 style="color: blue;">
    Comments:
  </h2>
  <br>
  <div style="width:90%;margin:0 auto; ">
    <% comments.each do |comment| %>
      <div class="col-sm-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <strong><%= link_to comment.user.username, user_path(:id => "#{comment.user.id}") %></strong>
            <span class="text-muted"><%=comment.created_at.getlocal.strftime("%m/%d/%Y at %I:%M %p")%></span>
          </div>
          <div class="panel-body text-muted" >
            <%=comment.review%>
          </div>
        </div>
      </div>
    <%end%>
</div>
  <%end%>

app/views/products/_new_comment.html.erb
<%if user_signed_in? && !current_user.admin?%>
  <h2 style="color: blue;">
    New Comment:
  </h2>
  <div class="col-sm-2"></div>
  <div class="col-sm-5">
    <%= form_for @comment, :url => product_comments_url(@product), :method => :post do |form| %>
    <div class="field" style="width: 50%">
      <%= form.text_area :review, :cols => 60, :rows => 4, style: "color: #000000;" , :required => true%>
    </div>
    <label style= "color: #000000;" >Rate me:</label>
    <!-- You're repeating this too much, you could've used an iterator, and pass in the rating. -->
    <%= form.radio_button :rating, 1, :id=>"one", :style=>"display:none;", :checked => false, class: "check-with-label"  %>
    <label style= "-webkit-text-stroke-width: 1px;-webkit-text-stroke-color: yellow;" for="one" class="label-for-check fas fa-star"></label>
    <%= form.radio_button :rating, 2, :id=>"two", :style=>"display:none;", :checked => false, class: "check-with-label"  %>
    <label style= "-webkit-text-stroke-width: 1px;-webkit-text-stroke-color: yellow;" for="two" class="label-for-check fas fa-star"></label>
    <%= form.radio_button :rating, 3, :id=>"thre", :style=>"display:none;", :checked => false, class: "check-with-label"  %>
    <label style= "-webkit-text-stroke-width: 1px;-webkit-text-stroke-color: yellow;" for="thre" class="label-for-check fas fa-star"></label>
    <%= form.radio_button :rating, 4, :id=>"four", :style=>"display:none;", :checked => false, class: "check-with-label"  %>
    <label style= "-webkit-text-stroke-width: 1px;-webkit-text-stroke-color: yellow;" for="four" class="label-for-check fas fa-star"></label>
    <%= form.radio_button :rating, 5, :id=>"five", :style=>"display:none;", :checked => false, class: "check-with-label"  %>
    <label style= "-webkit-text-stroke-width: 1px;-webkit-text-stroke-color: yellow;" for="five" class="label-for-check fas fa-star"></label>
    <div class="actions">
      <%= form.submit style: "color: #000000;"%>
    </div>
  <%end%>
</div>
<%end%>

app/views/products/_products_list.html.erb
<%  product.each do |prod| %>
  <div class="item  col-xs-4 col-lg-4">
    <div class="thumbnail">
      <%if prod.image_attach?%>
        <%= image_tag prod.medium_image, :class => 'group list-group-image' %>
        <%else%>
        <%= image_tag("null_image.png", size:"100x100", :alt => "not image", :class => 'group list-group-image') %>
      <%end%>
      <div class="caption">
        <h4 class="group inner list-group-item-heading"><%= prod.product_name %>
          <span style="text-align:right;">
            <% if user_signed_in? %>
              <!-- You're using this too much, maybe put it in a helper. -->
              <% if !current_user.admin? %>
                <% if prod.like_user(prod,current_user.id).empty?%>
                  <!-- Don't use inline styles! -->
                  <%= link_to like_products_path(:id => prod), method: :post do %>
                    <i class="far fa-thumbs-up btn btn-primary"></i>
                  <% end %> 
                  <!-- This is the correct syntax to use. Much more clearer. -->
                <% else %>
                  <%= link_to '<button class="far fa-thumbs-down btn btn-primary" style="color:red;" type="button" ></button>'.html_safe, like_product_path(:id => prod), method: :delete %>
                <% end %>
              <% end %>
            <%end%>
          </span>
        </h4>
        <p class="group inner list-group-item-text">Category:
          <%= prod.category_name %></p>
        <div class="row">
          <div class="col-xs-12 col-md-6">
            <p class="lead"><%= number_to_currency prod.price %></p>
          </div>

          <div class="col-xs-12 col-md-6">
            <p class="lead"><%= prod.like_size %>
              likes</p>
          </div>
          <% if user_signed_in? %>
            <!-- I think you could've put this in a partial, since it is only relevant when the user is an admin -->
            <% if current_user.admin?%>
              <div class="col-xs-12 col-md-6">
                <%= link_to '<button class="btn btn-success btn-block" type="button">Edit</button>'.html_safe, edit_product_url(:id => prod.id ) %>
              </div>
              <div class="col-xs-12 col-md-6">
                <%= link_to '<button class="btn btn-danger btn-block" type="button">Delete</button>'.html_safe, product_path(:id => prod.id),data: { confirm: "Are you sure?" }, method: :delete%>
              </div>
            <%else%>
              <div class="col-xs-12 col-md-6">
                <a href="products/<%= prod.id %> " class="btn btn-success btn-block">Buy</a>
              </div>
            <%end%>
          <%else%>
            <div class="col-xs-12 col-md-6">
              <a href="products/<%= prod.id %> " class="btn btn-success btn-block">Buy</a>
            </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<% if flash[:alert] %>
  <div class="alert alert-<%= flash[:alert_type]%>" role="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%=flash[:alert]%>
  </div>
<% end %>
<%= form_for product do |f| %>
<div style="width:50%; margin:0 auto; transform: translateY(10%);" class="thumbnail">
  <h1 style="color: blue;">
    Edit Product
  </h1>
  <div class="caption">
    <h4 class="group inner list-group-item-text"><strong>SKU:</strong>
      <%= product.sku %></h4>
    <div class="row">
      <div class="col-xs-12 col-md-3">
      </div>
      <div class="col-xs-12 col-md-9">
        <p class=""><strong>Product Name:</strong> <%= f.text_field :product_name, placeholder: 'Product Name',:required => true %></p>
        <p class=""><strong>Price:</strong> <%= f.number_field :price, :class => 'text_field' , :step => 0.01, min:0.1, value: product.price%></p>
        <p class=""><strong>Product quantity:</strong> <%= f.number_field :quantity, :class => 'text_field' , min:0, value: product.quantity%></p>
        <p><strong>Rating:</strong> <%= product.rating %> <i class="fas fa-star" style="color:yellow;"></i></p>
        <p class=""><strong>Product Category:</strong> <%= f.collection_select :category_id, category, :id, :name, :prompt => true, :selected => product.category_id || 2 %></p>
        <%if product.image.attached?%>
          <p class=""><strong>Image:</strong><%=image_tag product.image.variant(resize: "100x100") %></p>
        <%end%>
        <p class=""><strong>Change Image:</strong> <%= f.file_field :image%></p>
      </div>
      <div class="col-xs-12 col-md-4">
        </div>
      <div class="col-xs-12 col-md-4">
        <div class="actions">
          <%= f.submit "Submit", class: "btn btn-success btn-block"%>
        </div>
      </div>
    </div>
  </div>
  </div>
<% end %>
<%= render "list_comments"%>

app/views/products/index.html.erb
<% if flash[:alert] %>
  <div class="alert alert-<%= flash[:alert_type]%>" role="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%=flash[:alert]%>
  </div>
<% end %>
<br>
<br>
<br>
<%= link_to '<button class="btn btn-primary" type="button">See all</button>'.html_safe, products_path %>
<%= link_to '<button class="btn btn-primary fas fa-chevron-up" type="button"> Sort by name</button>'.html_safe, products_path(request.query_parameters.merge(:sort => "product_name ASC")) %>
<%= link_to '<button class="btn btn-primary fas fa-chevron-down" type="button"> Sort by name</button>'.html_safe, products_path(request.query_parameters.merge(:sort => "product_name DESC")) %>
<%= link_to '<button class="btn btn-primary fas fa-chevron-down" type="button"> Sort by likes</button>'.html_safe, products_path(request.query_parameters.merge(:sort => "likes_count DESC")) %>
<%= link_to '<button class="btn btn-primary fas fa-chevron-up" type="button"> Sort by likes</button>'.html_safe, products_path(request.query_parameters.merge(:sort => "likes_count ASC")) %>
<div class="col-xs-12 col-md-8"></div>
<div class="col-xs-12 col-md-3">
  <%= form_tag(products_path, method: :get) do %>
  <% request.query_parameters.each do |key, value| %>
    <%= hidden_field_tag(key, value) %>
  <% end %>
  <%= text_field_tag :term, params[:term], class: "form-control" %>
</div>
<div class="actions">
  <%= submit_tag 'Search', name: nil %>
</div>
<% end %>
<br>
<br>
<table align="center" border="0" width="100%">
  <tr>
    <td style="background-color: #F5F5F5;" width="16%" valign="top">
<div class="col-lg-11 col-md-11 col-sm-11 col-xs-11 shop-tab-menu">
<div class="list-group">
  <%  category.each do |cat| %>
    <%= link_to raw("<button class='list-group-item' type='button'><h4><i class='fa fa-chevron-right' aria-hidden='true'></i>#{cat.name}</h4></button>"), products_path(request.query_parameters.merge(:category => "#{cat.id}")) %>
    <br>
  <% end %>
</div>
</div>
</td>
<td style="background-color: #F5F5F5;" valign="top">
<div id="products" class="row list-group">
<%= render "products_list"%>
</div>
</td>
</tr>
</table>
<div class="apple_pagination">
<div class="page_info">
<%= page_entries_info product %>
</div>
<%= will_paginate product, :container => false%>
</div>

app/views/products/new.html.erb
<% if flash[:alert] %>
  <div class="alert alert-<%= flash[:alert_type]%>" role="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%=flash[:alert]%>
  </div>
<% end %>
<%= form_for product do |f| %>
<div style="width:50%; margin:0 auto; transform: translateY(10%);" class="thumbnail">
  <h1 style="color: blue;">
    New Product
  </h1>
  <div class="caption">
    <div class="row">
      <div class="col-xs-12 col-md-3">
      </div>
      <div class="col-xs-12 col-md-9">
        <p class=""><strong>Product Name:</strong> <%= f.text_field :product_name, placeholder: 'Product Name',:required => true %></p>
        <p class=""><strong>Price:</strong> <%= f.number_field :price, :class => 'text_field' , :step => 0.01, min:0.1, value: 0.1%></p>
        <p class=""><strong>Product quantity:</strong> <%= f.number_field :quantity, :class => 'text_field' , min:0, value: 1%></p>
        <p class=""><strong>Product Category:</strong> <%= f.collection_select(:category_id, category, :id, :name) %></p>
        <p class=""><strong>Image:</strong> <%= f.file_field :image%></p>
      </div>
      <div class="col-xs-12 col-md-4">
        </div>
      <div class="col-xs-12 col-md-4">
        <div class="actions">
          <%= f.hidden_field :sku, value:SecureRandom.uuid %>
          <%= f.hidden_field :status, value:'A' %>
          <%= f.submit "Submit", class: "btn btn-success btn-block"%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/products/show.html.erb
<%= form_for @shopping_cart, :url => shopping_carts_path(@shopping_cart), :method => :post do |f| %>
<div style="width:50%; margin:0 auto; transform: translateY(20%);" class="thumbnail">
  <%if product.image_attach?%>
    <%= image_tag product.big_image, :class => 'group list-group-image' %>
  <%end%>
  <div class="caption">
    <h2 class="font-weight-bold group inner list-group-item-heading"><%= product.product_name %></h2>
    <h4 class="group inner list-group-item-text">SKU:
      <%= product.sku %></h4>
    <p class="group inner list-group-item-text">Category:
      <%= product.category_name %></p>
    <p class="group inner list-group-item-text">Rating: <%= product.rating %>  <i class="fas fa-star" style="color:yellow;"></i></p>
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <p class="lead"><%= number_to_currency product.price %></p>
        <p class="lead" style="text-align: right;">
          <%=product.quantity%>
          products left
        </p>
      </div>
      <%if product.quantity > 0%>
        <div class="col-xs-12 col-md-2"></div>
        <div class="col-xs-12 col-md-3">
          <label>Quantity</label>
          <%= f.number_field :quantity, min:1, value: 1,class: "form-control", max: product.quantity%>
        </div>
        <div class="col-xs-12 col-md-2"></div>
        <div class="col-xs-12 col-md-4">
          <div class="actions">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.hidden_field :price, value: product.price %>
            <%= submit_tag("Add to Car", class: "btn btn-success btn-block") %>
          </div>
        </div>
      <%else%>
        <div class="col-xs-12 col-md-6">
          <p class="font-weight-bold h4" style="color:blue;text-align: right;">Out of Stock!</p>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>
<br><br>
<table align="center" border="0" width="90%">
  <tr>
    <td style="background-color: #F5F5F5;"><%= render "list_comments"%></td>
    <!-- this comments partial should be in the views comments' folder, not the products one. -->
  </tr>
  <tr>
    <td style="background-color: #F5F5F5;"><%= render "new_comment" %></td>
  </tr>
</table>