config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  root 'products#index'
  resources :products do
    resources :comments
  end
  resources :shopping_carts
  resources :orders
  resources :logs
  resources :order_details
  resources :like_products
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :products
      resources :sessions
      resources :users
    end
  end
  resources :users do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  validates :review, presence: true, allow_blank: false
  def comment_user(id)
    User.find(id).username
  end

  def comment_status(status)
    if status == 'A'
      'Activated'
    else
      'Disabled'
    end
  end
end

app/models/like_product.rb
class LikeProduct < ApplicationRecord
  belongs_to :user
  belongs_to :product, counter_cache: :likes_count
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details
  has_many :products, through: :order_details

  def self.seed_detail(product, last_order,id)
    product.each do |val|
      @detail = OrderDetail.new(order: last_order,
                                product: val.product,
                                quantity: val.quantity,
                                price: val.price,
                                status: 'P')
      ShoppingCart.where(user_id: id, product: val.product).destroy_all if @detail.save
    end
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, numericality: { greater_than_or_equal_to: 1 }, on: :create
end

app/models/product.rb
class Product < ApplicationRecord
  # relations
  belongs_to :category
  has_many :order_details
  has_many :log
  has_many :shopping_cart
  has_many :orders, through: :order_details
  has_many :like_products
  has_one_attached :image
  has_many :comments, as: :commentable

  # validations
  validates :sku, :product_name, presence: true
  validates :sku, uniqueness: true
  validates :quantity, numericality: {
    greater_than_or_equal_to: 0
  }, on: :create

  # scopes
  scope :sort_scope, ->(sort_val) { order(sort_val) }
  scope :term_scope, lambda { |term_val|
                       where('product_name ILIKE ?', "%#{term_val}%")
                     }
  scope :category_scope, ->(category_val) { where category_id: category_val }
  scope :page_scope, ->(page_val) { paginate(page: page_val, per_page: 8) }

  def category_name
    category.name
  end

  def image_attach?
    image.attached?
  end

  def big_image
    image.variant(resize: '200x200')
  end

  def medium_image
    image.variant(resize: '100x100')
  end

  def like_size
    like_products.size
  end

  def like_user(prod, id)
    prod.like_products.where(user_id: id)
  end

  def self.price_log(product, old_price, id)
    @log = Log.new(user_id: id,
                   description: 'The price of the product has change',
                   product_id: product.id, old_price: old_price,
                   new_price: product.price)
    @log.save
  end

  def rating
    comments.where("status='A' AND rating > 0 ").average(:rating)
  end
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :product

  validates :quantity, numericality: { greater_than_or_equal_to: 1 }, on: :create

  def self.update_quantity(quantity, prd, type)
    if type
      prd.quantity -= quantity.to_i
    else
      prd.quantity += quantity.to_i
    end
    prd.save
    if prd.quantity.to_i <= 3 && !prd.like_products.empty?
      SendNotificationsJob.perform_later(prd)
    end
  end

  def self.cart_list(user_id, product_id, quantity)
    list = ShoppingCart.find_by(user_id: user_id, product_id: product_id)
    list.quantity += quantity.to_i if list
    list
  end

  def category_name
    product.category.name
  end

  def product_name
    product.product_name
  end

  def prod_sku
    product.sku
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: %i[user admin]
  after_initialize :set_default_role

  def set_default_role
    self.role ||= :user if new_record?
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :shopping_cart
  has_many :log
  has_many :order
  has_many :comments, as: :commentable

  def rating
    comments.where("status='A' AND rating > 0").average(:rating)
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :user, :exist, :users, :comments
  helper_method :user, :users, :comments
  # before_action :admin_only, except: :show

  def index; end

  def show
    @comment = @user.comments.new
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

  def comments
    @comments =
      if action_name == 'index'
        Comment.all.where("commentable_type='User'")
      else
        @user.comments.where(status: 'A').includes(:user)
      end
  end

  def users
    @users = User.where(role: :user)
  end

  def user
    @user =
      if params[:id].present?
        User.find_by(id: params[:id])
      else
        current_user
      end
  end

  def exist
    error(user_path(id: current_user.id), 'User not available') unless @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def boostrap_class(alert)
    { success: 'alert-success', error: 'alert-danger', notice: 'alert-success', warning: 'alert-warning',
      danger: 'alert-danger', alert: 'alert-danger' }[alert.to_sym]
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{boostrap_class(msg_type.to_sym)} fade in") do
        concat(content_tag(:button, id: 'close-button', class: 'close', type: :button, data: { dismiss: 'alert' }, 'aria-label' => :Close) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/like_products_helper.rb
module LikeProductsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/rol_helper.rb
module RolHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.0/css/all.css" integrity="sha384-Mmxa0mLqhmOeaE8vgOSbKacftZcsNYDjQzuCOm6D02luYSzBG8vpaOykv9lFQ51Y" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-top navbar-fixed-top">
      <div class="container-fluid">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Snacks Shop</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <%if user_signed_in?%>
              <%if !current_user.admin? %>
                <ul class="nav navbar-nav  navbar-right">
                  <%= link_to " Shopping Cart", shopping_carts_path, style: "color: white;", class:"fas fa-shopping-cart" %>
                </ul>
              <%end%>
            <%else%>
              <ul class="nav navbar-nav  navbar-right">
                <%= link_to " Shopping Cart", shopping_carts_path, style: "color: white;", class:"fas fa-shopping-cart" %>
              </ul>
            <%end%>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile
                  <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <% if user_signed_in? %>
                    <li><%= link_to "Edit profile", edit_user_registration_path %></li>
                    <li><%= link_to "Review user", user_path(id: current_user.id) %></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                  <% else %>
                    <li><%= link_to "Sign up", new_user_registration_path %></li>
                    <li><%= link_to "Login", new_user_session_path %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav  navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products
                  <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "List", products_path %></li>
                </ul>
              </li>
            </ul>
            <%if user_signed_in?%>
              <%if current_user.admin? %>
                <ul class="nav navbar-nav  navbar-right">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin
                      <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Users reviews", users_path %></li>
                      <li><%= link_to "New Product", new_product_url %></li>
                    </ul>
                  </li>
                </ul>
              <%end%>
            <%end%>
          </div>
        </div>
      </div>
    </nav>
    <div id="main-container" class="container">
      <%= yield %>
    </div>
  </body>
</html>